# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/ui/askLePWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(506, 866)
        self.askLepWidget = QtWidgets.QWidget(Form)
        self.askLepWidget.setGeometry(QtCore.QRect(0, 0, 501, 851))
        self.askLepWidget.setStyleSheet("background-color: rgb(246, 247, 200);")
        self.askLepWidget.setObjectName("askLepWidget")
        self.askLeProgramLabel = QtWidgets.QLabel(self.askLepWidget)
        self.askLeProgramLabel.setGeometry(QtCore.QRect(30, 10, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.askLeProgramLabel.setFont(font)
        self.askLeProgramLabel.setObjectName("askLeProgramLabel")
        self.blackLine = QtWidgets.QFrame(self.askLepWidget)
        self.blackLine.setGeometry(QtCore.QRect(0, 70, 491, 8))
        self.blackLine.setStyleSheet("background-color: rgb(24, 35, 32);")
        self.blackLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.blackLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.blackLine.setObjectName("blackLine")
        self.logicalExpressionLabel = QtWidgets.QLabel(self.askLepWidget)
        self.logicalExpressionLabel.setGeometry(QtCore.QRect(30, 100, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.logicalExpressionLabel.setFont(font)
        self.logicalExpressionLabel.setStyleSheet("background-color: rgb(24, 35, 32);\n"
"color: rgb(255, 255, 242);")
        self.logicalExpressionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logicalExpressionLabel.setObjectName("logicalExpressionLabel")
        self.truthTableWidget = QtWidgets.QTableWidget(self.askLepWidget)
        self.truthTableWidget.setGeometry(QtCore.QRect(30, 190, 451, 211))
        self.truthTableWidget.setBaseSize(QtCore.QSize(0, 0))
        self.truthTableWidget.setStyleSheet("background-color: rgb(255, 255, 242);")
        self.truthTableWidget.setLineWidth(-3)
        self.truthTableWidget.setObjectName("truthTableWidget")
        self.truthTableWidget.setColumnCount(0)
        self.truthTableWidget.setRowCount(0)
        self.dnfFormTitleLabel = QtWidgets.QLabel(self.askLepWidget)
        self.dnfFormTitleLabel.setGeometry(QtCore.QRect(30, 440, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dnfFormTitleLabel.setFont(font)
        self.dnfFormTitleLabel.setStyleSheet("background-color: rgb(24, 35, 32);\n"
"color: rgb(255, 255, 242);")
        self.dnfFormTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dnfFormTitleLabel.setObjectName("dnfFormTitleLabel")
        self.dnfExpressionLabel = QtWidgets.QLabel(self.askLepWidget)
        self.dnfExpressionLabel.setGeometry(QtCore.QRect(30, 520, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dnfExpressionLabel.setFont(font)
        self.dnfExpressionLabel.setStyleSheet("color: rgb(24, 35, 32);\n"
"background-color: rgb(255, 255, 242);")
        self.dnfExpressionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dnfExpressionLabel.setObjectName("dnfExpressionLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.askLeProgramLabel.setText(_translate("Form", "Ask Le Program"))
        self.logicalExpressionLabel.setText(_translate("Form", "( ¬P ∨ ¬Q ) → ¬(Q ∧ R)"))
        self.truthTableWidget.setWhatsThis(_translate("Form", "Truth Table"))
        self.dnfFormTitleLabel.setText(_translate("Form", "DNF form:"))
        self.dnfExpressionLabel.setText(_translate("Form", "DNF form (also the thing above is a table widget)"))