# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/askLepPage.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_askLepPage(object):
    def setupUi(self, askLepPage):
        askLepPage.setObjectName("askLepPage")
        askLepPage.resize(1036, 671)
        askLepPage.setStyleSheet("background-color: rgb(255, 255, 242);\n"
"border-color: rgb(255, 255, 242);")
        self.gridLayout = QtWidgets.QGridLayout(askLepPage)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(askLepPage)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.expressionInput = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expressionInput.sizePolicy().hasHeightForWidth())
        self.expressionInput.setSizePolicy(sizePolicy)
        self.expressionInput.setMinimumSize(QtCore.QSize(300, 30))
        self.expressionInput.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(12)
        self.expressionInput.setFont(font)
        self.expressionInput.setObjectName("expressionInput")
        self.horizontalLayout_5.addWidget(self.expressionInput)
        self.searchButton = QtWidgets.QPushButton(self.frame)
        self.searchButton.setMinimumSize(QtCore.QSize(80, 30))
        self.searchButton.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.searchButton.setFont(font)
        self.searchButton.setStyleSheet("background-color: rgb(24, 35, 32);\n"
"color: rgb(246, 247, 200);\n"
"")
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_5.addWidget(self.searchButton)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.EnterExpressionLabel = QtWidgets.QLabel(askLepPage)
        self.EnterExpressionLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.EnterExpressionLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.EnterExpressionLabel.setFont(font)
        self.EnterExpressionLabel.setObjectName("EnterExpressionLabel")
        self.gridLayout.addWidget(self.EnterExpressionLabel, 0, 1, 1, 1)
        self.askLepTabWidget = QtWidgets.QTabWidget(askLepPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.askLepTabWidget.sizePolicy().hasHeightForWidth())
        self.askLepTabWidget.setSizePolicy(sizePolicy)
        self.askLepTabWidget.setMinimumSize(QtCore.QSize(300, 300))
        self.askLepTabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.askLepTabWidget.setStyleSheet("border-color: rgb(246, 247, 200);\n"
"alternate-background-color: rgb(255, 255, 255);\n"
"background-color: rgb(246, 247, 200);")
        self.askLepTabWidget.setObjectName("askLepTabWidget")
        self.howToTab = QtWidgets.QWidget()
        self.howToTab.setObjectName("howToTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.howToTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.howToTextBox = QtWidgets.QTextEdit(self.howToTab)
        self.howToTextBox.setEnabled(False)
        self.howToTextBox.setObjectName("howToTextBox")
        self.horizontalLayout.addWidget(self.howToTextBox)
        self.askLepTabWidget.addTab(self.howToTab, "")
        self.cheatSheetTab = QtWidgets.QWidget()
        self.cheatSheetTab.setObjectName("cheatSheetTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.cheatSheetTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.cheatSheetTab)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_3.addWidget(self.textEdit_2, 0, 0, 1, 1)
        self.askLepTabWidget.addTab(self.cheatSheetTab, "")
        self.myNotesTab = QtWidgets.QWidget()
        self.myNotesTab.setObjectName("myNotesTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.myNotesTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.myNotesTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 0, 0, 1, 1)
        self.askLepTabWidget.addTab(self.myNotesTab, "")
        self.gridLayout.addWidget(self.askLepTabWidget, 2, 1, 1, 1)
        self.askLepWidgetFrame = QtWidgets.QFrame(askLepPage)
        self.askLepWidgetFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.askLepWidgetFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.askLepWidgetFrame.setStyleSheet("background-color: rgb(255,255,242);\n"
"border-color: rgb(246, 247, 200);\n"
"")
        self.askLepWidgetFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.askLepWidgetFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.askLepWidgetFrame.setLineWidth(2)
        self.askLepWidgetFrame.setMidLineWidth(0)
        self.askLepWidgetFrame.setObjectName("askLepWidgetFrame")
        self.askLepLayout = QtWidgets.QHBoxLayout(self.askLepWidgetFrame)
        self.askLepLayout.setObjectName("askLepLayout")
        self.gridLayout.addWidget(self.askLepWidgetFrame, 1, 3, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)

        self.retranslateUi(askLepPage)
        self.askLepTabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(askLepPage)

    def retranslateUi(self, askLepPage):
        _translate = QtCore.QCoreApplication.translate
        askLepPage.setWindowTitle(_translate("askLepPage", "Frame"))
        self.searchButton.setText(_translate("askLepPage", "Search"))
        self.EnterExpressionLabel.setText(_translate("askLepPage", "Enter the Expression"))
        self.howToTextBox.setHtml(_translate("askLepPage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Fira Sans Semi-Light\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">How to use AskLep: </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">1) Variables are single English alphabet ,can be upper or lower case.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">2) Brackets () are used to alter precedence</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">3) Type the expression in the box above and press search </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">Logical Expressions:</span></p>\n"
"<table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\">\n"
"<tr>\n"
"<td>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Operator</span></p></td>\n"
"<td>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Char Form</span></p></td>\n"
"<td>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Maths form</span></p></td>\n"
"<td>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">CS form</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">AND</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">and</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">∧</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">&amp;&amp;</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">OR</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">or</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">∨</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">|</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">XOR</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">xor</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">⊕</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">!=</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">IMP</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">imp</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">→</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">=&gt;</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">IFF</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">iff</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">↔</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">==</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">TOP</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">top</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">⊤</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">True</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">BOT</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">bot</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">⊥</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">False</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">NOT</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">not</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">¬</span></p></td>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">!</span></p></td></tr>\n"
"<tr>\n"
"<td></td>\n"
"<td></td>\n"
"<td></td>\n"
"<td></td></tr></table>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">For every operator, users are allowed to use any form they choose. </span></p></body></html>"))
        self.askLepTabWidget.setTabText(self.askLepTabWidget.indexOf(self.howToTab), _translate("askLepPage", "How To"))
        self.textEdit_2.setHtml(_translate("askLepPage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Fira Sans Semi-Light\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">aw of Double Negation or Negation Elimination</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-6-Frame\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">¬</span><a name=\"MathJax-Span-14\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-15\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">¬</span><a name=\"MathJax-Span-16\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-17\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-18\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-19\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">¬(¬p)≡p</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">DeMorgan\'s Laws</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-7-Frame\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">¬</span><a name=\"MathJax-Span-23\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-24\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-25\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-26\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-27\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-28\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-29\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-30\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">¬</span><a name=\"MathJax-Span-31\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-32\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-33\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-34\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-35\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">¬</span><a name=\"MathJax-Span-36\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-37\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">¬(p∧q)≡(¬p)∨(¬q)</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-8-Frame\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">¬</span><a name=\"MathJax-Span-41\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-42\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-43\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-44\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-45\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-46\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-47\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-48\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">¬</span><a name=\"MathJax-Span-49\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-50\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-51\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-52\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-53\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">¬</span><a name=\"MathJax-Span-54\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-55\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">¬(p∨q)≡(¬p)∧(¬q)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">Commutative Laws for Conjunction, Disjunction and Biconditional</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-9-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-59\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-60\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-61\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-62\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-63\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-64\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∧q≡q∧p</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-10-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-68\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-69\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-70\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-71\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-72\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-73\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∨q≡q∨p</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-11-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-77\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">↔</span><a name=\"MathJax-Span-78\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-79\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-80\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-81\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">↔</span><a name=\"MathJax-Span-82\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p↔q≡q↔p</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">Associative Laws for Conjunction, Disjunction and Bicondional</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-12-Frame\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-86\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-87\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-88\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-89\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-90\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-91\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-92\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-93\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-94\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-95\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-96\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-97\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-98\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-99\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">(p∧q)∧r≡p∧(q∧r)</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-13-Frame\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-103\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-104\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-105\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-106\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-107\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-108\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-109\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-110\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-111\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-112\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-113\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-114\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-115\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-116\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">(p∨q)∨r≡p∨(q∨r)</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-14-Frame\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-120\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-121\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">↔</span><a name=\"MathJax-Span-122\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-123\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-124\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">↔</span><a name=\"MathJax-Span-125\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-126\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-127\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-128\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">↔</span><a name=\"MathJax-Span-129\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-130\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-131\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">↔</span><a name=\"MathJax-Span-132\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-133\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">(p↔q)↔r≡p↔(q↔</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#242729;\">r)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">Distributive Laws</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-15-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-137\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-138\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-139\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-140\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-141\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-142\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-143\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-144\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-145\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-146\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-147\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-148\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-149\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-150\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-151\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-152\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-153\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-154\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∨(q∧r)≡(p∨q)∧(p∨r)</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-16-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-158\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-159\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-160\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-161\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-162\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-163\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-164\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-165\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-166\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-167\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-168\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-169\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-170\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-171\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-172\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-173\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-174\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-175\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∧(q∨r)≡(p∧q)∨(p∧r)</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-17-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-179\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">→</span><a name=\"MathJax-Span-180\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-181\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-182\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-183\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-184\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-185\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-186\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-187\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-188\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">→</span><a name=\"MathJax-Span-189\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-190\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-191\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-192\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-193\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-194\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">→</span><a name=\"MathJax-Span-195\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-196\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p→(q∧r)≡(p→q)∧(p→r)</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-18-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-200\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">→</span><a name=\"MathJax-Span-201\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-202\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-203\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-204\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-205\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-206\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-207\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-208\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-209\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">→</span><a name=\"MathJax-Span-210\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-211\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-212\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-213\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-214\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-215\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">→</span><a name=\"MathJax-Span-216\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">r</span><a name=\"MathJax-Span-217\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p→(q∨r)≡(p→q)∨(p→r)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">Idempotent Laws</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-19-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-221\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-222\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-223\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-224\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∨p≡p</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-20-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-228\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-229\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-230\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-231\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∧p≡p</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">Identity Laws</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-21-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-235\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-236\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">F</span><a name=\"MathJax-Span-237\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-238\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∨F≡p</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-22-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-242\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-243\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">T</span><a name=\"MathJax-Span-244\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-245\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∧T≡p</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-23-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">T</span><a name=\"MathJax-Span-249\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">→</span><a name=\"MathJax-Span-250\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-251\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-252\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">T→p≡p</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">Inverse Laws</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-24-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-256\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-257\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-258\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">¬</span><a name=\"MathJax-Span-259\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-260\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-261\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-262\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">T</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∨(¬p)≡T</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-25-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-266\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-267\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-268\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">¬</span><a name=\"MathJax-Span-269\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-270\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-271\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-272\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">F</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∧(¬p)≡F</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">Domination Laws</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-26-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-276\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-277\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">T</span><a name=\"MathJax-Span-278\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-279\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">T</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∨T≡T</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-27-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-283\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-284\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">F</span><a name=\"MathJax-Span-285\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-286\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">F</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∧F≡F</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">Absortion Laws</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-28-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-290\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-291\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-292\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-293\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-294\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-295\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-296\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-297\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∨(p∧q)≡p</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-29-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-301\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-302\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-303\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-304\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-305\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-306\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-307\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-308\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p∧(p∨q)≡p</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">The &quot;Switcheroo&quot; Law</span><a name=\"MathJax-Element-30-Frame\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#242729; background-color:#ffffff;\">(</span><a name=\"MathJax-Span-316\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#242729; background-color:#ffffff;\">2</span><a name=\"MathJax-Span-317\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#242729; background-color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#242729; background-color:#ffffff;\">(2)</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-31-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-321\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">→</span><a name=\"MathJax-Span-322\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-323\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-324\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-325\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">¬</span><a name=\"MathJax-Span-326\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-327\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-328\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-329\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p→q≡(¬p)∨q</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">Equivalence of the Contrapositive of a Conditional Statement</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-32-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-333\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">→</span><a name=\"MathJax-Span-334\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-335\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-336\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-337\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">¬</span><a name=\"MathJax-Span-338\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-339\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-340\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">→</span><a name=\"MathJax-Span-341\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-342\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">¬</span><a name=\"MathJax-Span-343\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-344\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p→q≡(¬q)→(¬p)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">Meaning of Biconditional</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-33-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-348\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">↔</span><a name=\"MathJax-Span-349\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-350\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-351\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-352\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-353\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">→</span><a name=\"MathJax-Span-354\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-355\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><a name=\"MathJax-Span-356\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-357\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-358\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-359\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">→</span><a name=\"MathJax-Span-360\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-361\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p↔q≡(p→q)∧(q→p)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">Iteration Rule</span><a name=\"MathJax-Element-34-Frame\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#242729; background-color:#ffffff;\">(</span><a name=\"MathJax-Span-369\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#242729; background-color:#ffffff;\">3</span><a name=\"MathJax-Span-370\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#242729; background-color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#242729; background-color:#ffffff;\">(3)</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-35-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-374\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-375\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p≡p</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Georgia,Times New Roman,Times,serif\'; font-size:12pt; color:#242729; background-color:#ffffff;\">Conditional Expansion Laws</span><a name=\"MathJax-Element-36-Frame\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#242729; background-color:#ffffff;\">(</span><a name=\"MathJax-Span-383\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#242729; background-color:#ffffff;\">4</span><a name=\"MathJax-Span-384\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#242729; background-color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#242729; background-color:#ffffff;\">(4)</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-37-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#242729;\">p</span><a name=\"MathJax-Span-388\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#242729;\">→</span><a name=\"MathJax-Span-389\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#242729;\">q</span><a name=\"MathJax-Span-390\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-391\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-392\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">↔</span><a name=\"MathJax-Span-393\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-394\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-395\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∧</span><a name=\"MathJax-Span-396\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-397\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#ffffff;\">p→q≡p↔(p∧q)</span></p>\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:18px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#000000;\"><a name=\"MathJax-Element-38-Frame\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-401\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">→</span><a name=\"MathJax-Span-402\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-403\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">≡</span><a name=\"MathJax-Span-404\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-405\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">↔</span><a name=\"MathJax-Span-406\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">(</span><a name=\"MathJax-Span-407\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">p</span><a name=\"MathJax-Span-408\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">∨</span><a name=\"MathJax-Span-409\"></a><span style=\" font-family:\'MathJax_Math-italic\'; font-size:12pt; color:#ffffff;\">q</span><a name=\"MathJax-Span-410\"></a><span style=\" font-family:\'MathJax_Main\'; font-size:12pt; color:#ffffff;\">)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"><br /></span></p></body></html>"))
        self.askLepTabWidget.setTabText(self.askLepTabWidget.indexOf(self.cheatSheetTab), _translate("askLepPage", "Cheat Sheet"))
        self.textEdit.setPlaceholderText(_translate("askLepPage", "Type your notes here"))
        self.askLepTabWidget.setTabText(self.askLepTabWidget.indexOf(self.myNotesTab), _translate("askLepPage", "My Notes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    askLepPage = QtWidgets.QFrame()
    ui = Ui_askLepPage()
    ui.setupUi(askLepPage)
    askLepPage.show()
    sys.exit(app.exec_())
