# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/ui/taskMaking.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_taskMakingFrame(object):
    def setupUi(self, taskMakingFrame):
        taskMakingFrame.setObjectName("taskMakingFrame")
        taskMakingFrame.resize(803, 641)
        self.verticalLayout = QtWidgets.QVBoxLayout(taskMakingFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topFrame = QtWidgets.QFrame(taskMakingFrame)
        self.topFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topFrame.setObjectName("topFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deleteButton = QtWidgets.QPushButton(self.topFrame)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.saveButton = QtWidgets.QPushButton(self.topFrame)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.topFrame)
        self.expressionFrame = QtWidgets.QFrame(taskMakingFrame)
        self.expressionFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.expressionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.expressionFrame.setObjectName("expressionFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.expressionFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.expressionInput = QtWidgets.QLineEdit(self.expressionFrame)
        self.expressionInput.setText("")
        self.expressionInput.setObjectName("expressionInput")
        self.horizontalLayout_3.addWidget(self.expressionInput)
        self.ifValidLabel = QtWidgets.QLabel(self.expressionFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ifValidLabel.setFont(font)
        self.ifValidLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.ifValidLabel.setObjectName("ifValidLabel")
        self.horizontalLayout_3.addWidget(self.ifValidLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.expressionFrame)
        self.taskDescriptionInput = QtWidgets.QTextEdit(taskMakingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskDescriptionInput.sizePolicy().hasHeightForWidth())
        self.taskDescriptionInput.setSizePolicy(sizePolicy)
        self.taskDescriptionInput.setMinimumSize(QtCore.QSize(0, 0))
        self.taskDescriptionInput.setMaximumSize(QtCore.QSize(16777215, 100))
        self.taskDescriptionInput.setObjectName("taskDescriptionInput")
        self.verticalLayout.addWidget(self.taskDescriptionInput)
        self.answersScrollArea = QtWidgets.QScrollArea(taskMakingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answersScrollArea.sizePolicy().hasHeightForWidth())
        self.answersScrollArea.setSizePolicy(sizePolicy)
        self.answersScrollArea.setMinimumSize(QtCore.QSize(500, 300))
        self.answersScrollArea.setLineWidth(0)
        self.answersScrollArea.setWidgetResizable(True)
        self.answersScrollArea.setObjectName("answersScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 783, 375))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.answerScrollBarContents = QtWidgets.QVBoxLayout()
        self.answerScrollBarContents.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.answerScrollBarContents.setSpacing(0)
        self.answerScrollBarContents.setObjectName("answerScrollBarContents")
        self.verticalLayout_2.addLayout(self.answerScrollBarContents)
        self.answersScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.answersScrollArea)
        self.answerButtonFrame = QtWidgets.QFrame(taskMakingFrame)
        self.answerButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.answerButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.answerButtonFrame.setObjectName("answerButtonFrame")
        self.answersLayout = QtWidgets.QHBoxLayout(self.answerButtonFrame)
        self.answersLayout.setObjectName("answersLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.answersLayout.addItem(spacerItem4)
        self.addAnswerButton = QtWidgets.QPushButton(self.answerButtonFrame)
        self.addAnswerButton.setObjectName("addAnswerButton")
        self.answersLayout.addWidget(self.addAnswerButton)
        self.removeAnswerButton = QtWidgets.QPushButton(self.answerButtonFrame)
        self.removeAnswerButton.setObjectName("removeAnswerButton")
        self.answersLayout.addWidget(self.removeAnswerButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.answersLayout.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.answerButtonFrame)

        self.retranslateUi(taskMakingFrame)
        QtCore.QMetaObject.connectSlotsByName(taskMakingFrame)

    def retranslateUi(self, taskMakingFrame):
        _translate = QtCore.QCoreApplication.translate
        taskMakingFrame.setWindowTitle(_translate("taskMakingFrame", "Frame"))
        self.deleteButton.setText(_translate("taskMakingFrame", "Delete"))
        self.saveButton.setText(_translate("taskMakingFrame", "Save"))
        self.expressionInput.setPlaceholderText(_translate("taskMakingFrame", "Enter an expression (leave blank if not needed)"))
        self.ifValidLabel.setText(_translate("taskMakingFrame", "Invalid Expression"))
        self.taskDescriptionInput.setHtml(_translate("taskMakingFrame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.taskDescriptionInput.setPlaceholderText(_translate("taskMakingFrame", "Enter task description"))
        self.addAnswerButton.setText(_translate("taskMakingFrame", "Add an answer"))
        self.removeAnswerButton.setText(_translate("taskMakingFrame", "Remove answer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    taskMakingFrame = QtWidgets.QFrame()
    ui = Ui_taskMakingFrame()
    ui.setupUi(taskMakingFrame)
    taskMakingFrame.show()
    sys.exit(app.exec_())
