# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/ui/taskMaking.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_taskMakingFrame(object):
    def setupUi(self, taskMakingFrame):
        taskMakingFrame.setObjectName("taskMakingFrame")
        taskMakingFrame.resize(744, 551)
        self.verticalLayout = QtWidgets.QVBoxLayout(taskMakingFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topFrame = QtWidgets.QFrame(taskMakingFrame)
        self.topFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topFrame.setObjectName("topFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelButton = QtWidgets.QPushButton(self.topFrame)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.saveButton = QtWidgets.QPushButton(self.topFrame)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.taskNameLabel = QtWidgets.QLabel(self.topFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.taskNameLabel.setFont(font)
        self.taskNameLabel.setObjectName("taskNameLabel")
        self.horizontalLayout.addWidget(self.taskNameLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.topFrame)
        self.questionStatementTextEdit = QtWidgets.QTextEdit(taskMakingFrame)
        self.questionStatementTextEdit.setObjectName("questionStatementTextEdit")
        self.verticalLayout.addWidget(self.questionStatementTextEdit)
        self.expressionFrame = QtWidgets.QFrame(taskMakingFrame)
        self.expressionFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.expressionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.expressionFrame.setObjectName("expressionFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.expressionFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.expressionLineEdit = QtWidgets.QLineEdit(self.expressionFrame)
        self.expressionLineEdit.setText("")
        self.expressionLineEdit.setObjectName("expressionLineEdit")
        self.horizontalLayout_3.addWidget(self.expressionLineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.expressionFrame)
        self.answersFrame = QtWidgets.QFrame(taskMakingFrame)
        self.answersFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.answersFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.answersFrame.setObjectName("answersFrame")
        self.answersLayout = QtWidgets.QHBoxLayout(self.answersFrame)
        self.answersLayout.setObjectName("answersLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.answersLayout.addItem(spacerItem4)
        self.pushButton = QtWidgets.QPushButton(self.answersFrame)
        self.pushButton.setObjectName("pushButton")
        self.answersLayout.addWidget(self.pushButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.answersLayout.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.answersFrame)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)

        self.retranslateUi(taskMakingFrame)
        QtCore.QMetaObject.connectSlotsByName(taskMakingFrame)

    def retranslateUi(self, taskMakingFrame):
        _translate = QtCore.QCoreApplication.translate
        taskMakingFrame.setWindowTitle(_translate("taskMakingFrame", "Frame"))
        self.cancelButton.setText(_translate("taskMakingFrame", "fuk go back"))
        self.saveButton.setText(_translate("taskMakingFrame", "Save"))
        self.taskNameLabel.setText(_translate("taskMakingFrame", "Task name"))
        self.questionStatementTextEdit.setPlaceholderText(_translate("taskMakingFrame", "Enter task description"))
        self.expressionLineEdit.setPlaceholderText(_translate("taskMakingFrame", "Enter an expression (leave blank if not needed)"))
        self.pushButton.setText(_translate("taskMakingFrame", "Add an answer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    taskMakingFrame = QtWidgets.QFrame()
    ui = Ui_taskMakingFrame()
    ui.setupUi(taskMakingFrame)
    taskMakingFrame.show()
    sys.exit(app.exec_())
