# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/testMaking.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_testMakingPage(object):
    def setupUi(self, testMakingPage):
        testMakingPage.setObjectName("testMakingPage")
        testMakingPage.resize(804, 738)
        testMakingPage.setStyleSheet("background-color: rgb(255, 255, 242);\n"
"border-color: rgb(255, 255, 242);")
        self.gridLayout = QtWidgets.QGridLayout(testMakingPage)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(testMakingPage)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.testNameLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.testNameLabel.setFont(font)
        self.testNameLabel.setLineWidth(0)
        self.testNameLabel.setObjectName("testNameLabel")
        self.verticalLayout.addWidget(self.testNameLabel)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.testNameInput = QtWidgets.QPlainTextEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testNameInput.sizePolicy().hasHeightForWidth())
        self.testNameInput.setSizePolicy(sizePolicy)
        self.testNameInput.setMinimumSize(QtCore.QSize(100, 0))
        self.testNameInput.setMaximumSize(QtCore.QSize(800, 40))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(11)
        self.testNameInput.setFont(font)
        self.testNameInput.setStyleSheet("border-color: rgb(246, 247, 200)")
        self.testNameInput.setFrameShape(QtWidgets.QFrame.Panel)
        self.testNameInput.setFrameShadow(QtWidgets.QFrame.Plain)
        self.testNameInput.setLineWidth(2)
        self.testNameInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.testNameInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.testNameInput.setObjectName("testNameInput")
        self.gridLayout_2.addWidget(self.testNameInput, 0, 0, 1, 1)
        self.testDescriptionInput = QtWidgets.QPlainTextEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testDescriptionInput.sizePolicy().hasHeightForWidth())
        self.testDescriptionInput.setSizePolicy(sizePolicy)
        self.testDescriptionInput.setMinimumSize(QtCore.QSize(100, 60))
        self.testDescriptionInput.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(11)
        self.testDescriptionInput.setFont(font)
        self.testDescriptionInput.setStyleSheet("border-color: rgb(246, 247, 200)")
        self.testDescriptionInput.setFrameShape(QtWidgets.QFrame.Panel)
        self.testDescriptionInput.setFrameShadow(QtWidgets.QFrame.Plain)
        self.testDescriptionInput.setLineWidth(2)
        self.testDescriptionInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.testDescriptionInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.testDescriptionInput.setTabChangesFocus(False)
        self.testDescriptionInput.setPlainText("")
        self.testDescriptionInput.setObjectName("testDescriptionInput")
        self.gridLayout_2.addWidget(self.testDescriptionInput, 1, 0, 1, 1)
        self.addTaskButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addTaskButton.sizePolicy().hasHeightForWidth())
        self.addTaskButton.setSizePolicy(sizePolicy)
        self.addTaskButton.setMinimumSize(QtCore.QSize(0, 40))
        self.addTaskButton.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.addTaskButton.setFont(font)
        self.addTaskButton.setStyleSheet("background-color: rgb(24, 35, 32);\n"
"color: rgb(246, 247, 200);\n"
"")
        self.addTaskButton.setObjectName("addTaskButton")
        self.gridLayout_2.addWidget(self.addTaskButton, 0, 1, 1, 1)
        self.finishButton = QtWidgets.QPushButton(self.frame_2)
        self.finishButton.setMinimumSize(QtCore.QSize(0, 40))
        self.finishButton.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.finishButton.setFont(font)
        self.finishButton.setStyleSheet("background-color: rgb(255, 253, 78);\n"
"border-color: rgb(255, 253, 78);\n"
"selection-color:rgb(233, 234, 189);\n"
"selection-background-color: rgb(233, 234, 189);")
        self.finishButton.setObjectName("finishButton")
        self.gridLayout_2.addWidget(self.finishButton, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.taskMakingScrollArea = QtWidgets.QScrollArea(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskMakingScrollArea.sizePolicy().hasHeightForWidth())
        self.taskMakingScrollArea.setSizePolicy(sizePolicy)
        self.taskMakingScrollArea.setMinimumSize(QtCore.QSize(250, 200))
        self.taskMakingScrollArea.setMaximumSize(QtCore.QSize(1500, 16777215))
        self.taskMakingScrollArea.setStyleSheet("border-color: rgb(246, 247, 200);\n"
"background-color: rgb(255, 255, 242);")
        self.taskMakingScrollArea.setFrameShape(QtWidgets.QFrame.Panel)
        self.taskMakingScrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.taskMakingScrollArea.setLineWidth(1)
        self.taskMakingScrollArea.setWidgetResizable(True)
        self.taskMakingScrollArea.setObjectName("taskMakingScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 387, 577))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.taskScrollBarContents = QtWidgets.QVBoxLayout()
        self.taskScrollBarContents.setSpacing(24)
        self.taskScrollBarContents.setObjectName("taskScrollBarContents")
        self.verticalLayout_2.addLayout(self.taskScrollBarContents)
        self.taskMakingScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.taskMakingScrollArea)
        self.gridLayout.addWidget(self.frame, 12, 3, 1, 1)
        self.frame_3 = QtWidgets.QFrame(testMakingPage)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(900, 40))
        self.frame_4.setStyleSheet("background-color : rgb(246, 247, 200)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.askLepInput = QtWidgets.QLineEdit(self.frame_4)
        self.askLepInput.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.askLepInput.setFont(font)
        self.askLepInput.setObjectName("askLepInput")
        self.horizontalLayout.addWidget(self.askLepInput)
        self.askLepButton = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.askLepButton.sizePolicy().hasHeightForWidth())
        self.askLepButton.setSizePolicy(sizePolicy)
        self.askLepButton.setMinimumSize(QtCore.QSize(100, 30))
        self.askLepButton.setMaximumSize(QtCore.QSize(900, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setBold(True)
        font.setWeight(75)
        self.askLepButton.setFont(font)
        self.askLepButton.setStyleSheet("background-color: rgb(23, 161, 145);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.askLepButton.setObjectName("askLepButton")
        self.horizontalLayout.addWidget(self.askLepButton)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.askLepWidgetFrame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.askLepWidgetFrame.sizePolicy().hasHeightForWidth())
        self.askLepWidgetFrame.setSizePolicy(sizePolicy)
        self.askLepWidgetFrame.setMinimumSize(QtCore.QSize(50, 400))
        self.askLepWidgetFrame.setMaximumSize(QtCore.QSize(900, 16777215))
        self.askLepWidgetFrame.setStyleSheet("background-color: rgb(246, 247, 200);\n"
"border-color: rgb(246, 247, 200);\n"
"")
        self.askLepWidgetFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.askLepWidgetFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.askLepWidgetFrame.setLineWidth(2)
        self.askLepWidgetFrame.setObjectName("askLepWidgetFrame")
        self.askLepLayout = QtWidgets.QVBoxLayout(self.askLepWidgetFrame)
        self.askLepLayout.setObjectName("askLepLayout")
        self.verticalLayout_3.addWidget(self.askLepWidgetFrame)
        self.gridLayout.addWidget(self.frame_3, 12, 4, 1, 1)

        self.retranslateUi(testMakingPage)
        QtCore.QMetaObject.connectSlotsByName(testMakingPage)

    def retranslateUi(self, testMakingPage):
        _translate = QtCore.QCoreApplication.translate
        testMakingPage.setWindowTitle(_translate("testMakingPage", "Frame"))
        self.testNameLabel.setText(_translate("testMakingPage", "Test Name"))
        self.testNameInput.setPlaceholderText(_translate("testMakingPage", "Input test name"))
        self.testDescriptionInput.setPlaceholderText(_translate("testMakingPage", "Input test description"))
        self.addTaskButton.setText(_translate("testMakingPage", "  Add Task  "))
        self.finishButton.setText(_translate("testMakingPage", "  Finish  "))
        self.askLepInput.setPlaceholderText(_translate("testMakingPage", "Type expression for Ask Lep "))
        self.askLepButton.setText(_translate("testMakingPage", "Ask Lep"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    testMakingPage = QtWidgets.QFrame()
    ui = Ui_testMakingPage()
    ui.setupUi(testMakingPage)
    testMakingPage.show()
    sys.exit(app.exec_())
